# Project properties
group = com.example
name = ExamplePlugin
version = 1.0.0
description = Your plugin description here.
website = https://example.com
main = com.example.plugin.ExamplePlugin

# Gradle properties
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx3G -XX:+UseG1GC -Dfile.encoding=UTF-8